security:
  encoders:
    App\Security\Customer:
      algorithm: auto

  providers:
    app_user_provider:
      id: App\Security\CustomerProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator

  access_control:
    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
