admin_api_audit_log:
  resource: 'App\Admin\Controller\Api\AuditLogController'
  type: annotation
  prefix: /api/admin/audit-log

admin_api_category:
  resource: 'App\Admin\Controller\Api\CategoryController'
  type: annotation
  prefix: /api/admin/category

admin_api_course:
  resource: 'App\Admin\Controller\Api\CourseController'
  type: annotation
  prefix: /api/admin/course

admin_api_course_option:
  resource: 'App\Admin\Controller\Api\CourseOptionController'
  type: annotation
  prefix: /api/admin/course/options

admin_api_course_review:
  resource: 'App\Admin\Controller\Api\CourseReviewController'
  type: annotation
  prefix: /api/admin/course/reviews

admin_api_document:
  resource: 'App\Admin\Controller\Api\DocumentController'
  type: annotation
  prefix: /api/admin/document

admin_api_entity:
  resource: 'App\Admin\Controller\Api\EntityController'
  type: annotation
  prefix: /api/admin/entity

admin_api_faq:
  resource: 'App\Admin\Controller\Api\FaqController'
  type: annotation
  prefix: /api/admin/faq

admin_api_menu:
  resource: 'App\Admin\Controller\Api\MenuController'
  type: annotation
  prefix: /api/admin/menu

admin_api_notification:
  resource: 'App\Admin\Controller\Api\NotificationController'
  type: annotation
  prefix: /api/admin/notification

admin_api_role:
  resource: 'App\Admin\Controller\Api\RoleController'
  type: annotation
  prefix: /api/admin/role

admin_api_tag:
  resource: 'App\Admin\Controller\Api\TagController'
  type: annotation
  prefix: /api/admin/tag

admin_api_user:
  resource: 'App\Admin\Controller\Api\UserController'
  type: annotation
  prefix: /api/admin/user

admin_api_customer:
  resource: 'App\Admin\Controller\Api\CustomerController'
  type: annotation
  prefix: /api/admin/customer

admin_api_order:
  resource: 'App\Admin\Controller\Api\OrderController'
  type: annotation
  prefix: /api/admin/order

admin_api_rel:
  resource: 'App\Admin\Controller\Api\RelationshipController'
  type: annotation
  prefix: /api/admin

course:
  resource: 'App\Controller\CourseController'
  type: annotation

customer:
  resource: 'App\Controller\CustomerController'
  type: annotation

order:
  resource: 'App\Controller\OrderController'
  type: annotation

default:
  resource: 'App\Controller\DefaultController'
  type: annotation
