api_audit_log:
  resource: 'App\Controller\AuditLogController'
  type: annotation
  prefix: /api/audit-log

api_category:
  resource: 'App\Controller\CategoryController'
  type: annotation
  prefix: /api/category

api_course:
  resource: 'App\Controller\CourseController'
  type: annotation
  prefix: /api/course

api_course_option:
  resource: 'App\Controller\CourseOptionController'
  type: annotation
  prefix: /api/course/options

api_course_review:
  resource: 'App\Controller\CourseReviewController'
  type: annotation
  prefix: /api/course/reviews

api_document:
  resource: 'App\Controller\DocumentController'
  type: annotation
  prefix: /api/document

api_entity:
  resource: 'App\Controller\EntityController'
  type: annotation
  prefix: /api/entity

api_faq:
  resource: 'App\Controller\FaqController'
  type: annotation
  prefix: /api/faq

api_menu:
  resource: 'App\Controller\MenuController'
  type: annotation
  prefix: /api/menu

api_notification:
  resource: 'App\Controller\NotificationController'
  type: annotation
  prefix: /api/notification

api_role:
  resource: 'App\Controller\RoleController'
  type: annotation
  prefix: /api/role

api_tag:
  resource: 'App\Controller\TagController'
  type: annotation
  prefix: /api/tag

api_user:
  resource: 'App\Controller\UserController'
  type: annotation
  prefix: /api/user

api_customer:
  resource: 'App\Controller\CustomerController'
  type: annotation
  prefix: /api/customer

api_order:
  resource: 'App\Controller\OrderController'
  type: annotation
  prefix: /api/order

api_auth:
  resource: 'App\Controller\AuthController'
  type: annotation
  prefix: /api/auth

api_rel:
  resource: 'App\Controller\RelationshipController'
  type: annotation
  prefix: /api/admin

default:
  resource: 'App\Controller\DefaultController'
  type: annotation
