parameters:
  env(DB_HOST): "localhost"
  env(DB_PORT): "5432"
  env(DB_NAME): "oo"
  env(DB_USERNAME): "root"
  env(DB_PASSWORD): "123456"
  env(STRIPE_SKEY): "sk_test_HIGbrbeZfLwjL7KPMdf0eLfX00srDkFzZM"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Event,Entity,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Database:
    arguments:
      - host: '%env(DB_HOST)%'
        port: '%env(int:DB_PORT)%'
        dbname: '%env(DB_NAME)%'
        username: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'

  App\Listener\TrackerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onResponse, }

  App\Listener\ParseJsonRequest:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: parseRequest, }

  App\Listener\RequestIdentifier:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: identifyRequest, }
      - { name: kernel.event_listener, event: kernel.response, method: identifyResponse, }