pipelines:
  default:
    - parallel:
        - step:
            name: Backend tests
            image: php:latest
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - composer test

        - step:
            name: Frontend tests
            image: node:latest
            caches:
              - node
            script:
              - npm install
              - npm test
              - npm run lint:check

    - step:
        name: Deploy to staging
        image: ruby:2.4.6
        deployment: Staging
        caches:
          - bundler
        script:
          - bundle install
          - cap staging deploy

    - step:
        name: Deploy to production
        image: ruby:2.4.6
        deployment: Production
        trigger: manual
        caches:
          - bundler
        script:
          - bundle install
          - cap production deploy

definitions:
  caches:
    bundler: ./vendor
