monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_404s:
        - ^/
    nested:
      type: stream
      path: "%kernel.logs_dir%/error.log"
      level: debug
      channels: ["!event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
    stderr:
      type: error_log
      level: debug
      channels: ["!event"]
