---
- name: add PPA repository
  apt_repository:
    repo: 'ppa:nginx/mainline'
    update_cache: yes

- name: install nginx
  apt:
    state: latest
    name: nginx

- name: create nginx mime types
  template:
    src: mime.types.j2
    dest: '{{ nginx_path }}/mime.types'

- name: create nginx.conf
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_path }}/nginx.conf'
  notify: reload nginx

- name: disable default server
  file:
    path: '{{ nginx_path }}/sites-enabled/default'
    state: absent
  notify: reload nginx

- name: create virtual host configuration
  template:
    src: vhost.conf.j2
    dest: '{{ nginx_path }}/sites-available/{{ app_name }}.conf'
  notify: reload nginx

- name: enable virtual host
  file:
    src: '{{ nginx_path }}/sites-available/{{ app_name }}.conf'
    dest: '{{ nginx_path }}/sites-enabled/{{ app_name }}.conf'
    owner: root
    group: root
    state: link
  notify: reload nginx

- name: configure nginx to start on boot
  service:
    name: nginx
    enabled: yes
    state: started
    use: service
